### PR TITLE
Add `Keystore` component

### PR DESCRIPTION
**Pull request by vlopes11**
The keys scheme will be provided by the node and should be responsible
for the messages validity.

With the introduction of `Keystore`, `(Key, ValidatorId)` are
deprecated.

The mock implementation is moving closer to the fuel infrastructure, so
it uses `fuel-crypto` and `fuel-types`.

### CODE REVIEW

**Comment by vlopes11** [comment]
Blocked by https://github.com/FuelLabs/fuel-crypto/pull/2

**Review by adlerjohn — COMMENTED** [review]
What's the purpose of this crate? If it's just general handling signature, it shouldn't be part of `fuel-bft`, because the SDK will also need to have a keyring (aka wallet). It should be a separate crate, e.g. `fuel-keyring-rs`.

**Comment by vlopes11** [comment]
Blocked by https://github.com/FuelLabs/fuel-types/pull/24

**Review by adlerjohn — COMMENTED** [review]
No immediate comments, will defer to @Voxelot and @rakita

**Comment by vlopes11** [comment]
Superseded by https://github.com/FuelLabs/fuel-bft/pull/9

**Pull request closed without merging**
